-- 1

CREATE DATABASE IF NOT EXISTS Tecnuque;

USE Tecnuque;

CREATE TABLE IF NOT EXISTS Product(
maker VARCHAR(10) NOT NULL,
model VARCHAR(50) NOT NULL,
type VARCHAR(50) NOT NULL,
PRIMARY KEY(model)
);

USE Tecnuque;

CREATE TABLE IF NOT EXISTS PC(
code INT NOT NULL PRIMARY KEY,
model VARCHAR(50) not null,
speed SMALLINT NOT NULL,
ram SMALLINT NOT NULL,
hd REAL NOT NULL,
cd VARCHAR(10) NOT NULL,
price DECIMAL(10, 2),
FOREIGN KEY(model) REFERENCES product(model)
);

USE Tecnuque;

CREATE TABLE IF NOT EXISTS Laptop(
code INT NOT NULL PRIMARY KEY,
model VARCHAR(50) NOT NULL,
speed SMALLINT NOT NULL,
ram SMALLINT NOT NULL,
hd REAL NOT NULL,
price DECIMAL(10, 2),
screen TINYINT NOT NULL,
FOREIGN KEY(model) REFERENCES product(model)
);

USE Tecnuque;

CREATE TABLE IF NOT EXISTS Printer(
code INT NOT NULL PRIMARY KEY,
model VARCHAR(50) NOT NULL,
color VARCHAR(1) NOT NULL,
type VARCHAR(10) NOT NULL,
price DECIMAL(10, 2),
FOREIGN KEY(model) REFERENCES product(model)
);

    




